const CANADA_MUNICIPALITIES = {
  "Alberta": [
    "Airdrie","Athabasca","Banff","Barrhead","Beaverlodge","Black Diamond","Blackfalds","Bon Accord","Bonnyville","Bow Island","Brooks","Calgary","Calmar","Camrose","Canmore","Cardston","Carstairs","Chestermere","Claresholm","Coaldale","Coalhurst","Cochrane","Cold Lake","Crossfield","Crowsnest Pass","Devon","Didsbury","Drayton Valley","Drumheller","Eckville","Edmonton","Edson","Elk Point","Falher","Fort MacLeod","Fort McMurray","Fort Saskatchewan","Fox Creek","Gibbons","Grande Cache","Grande Prairie","Grimshaw","Hanna","High Level","High Prairie","High River","Hinton","Irricana","Killam","Lacombe","Lamont","Leduc","Lethbridge","Lloydminster","Magrath","Manning","Mayerthorpe","Medicine Hat","Millet","Morinville","Mundare","Nanton","Okotoks","Olds","Onoway","Peace River","Penhold","Pincher Creek","Ponoka","Provost","Raymond","Red Deer","Redwater","Rimbey","Rocky Mountain House","Rockey View County","Sexsmith","Slave Lake","Smoky Lake","Spirit River","Spruce Grove","St. Albert","St. Paul","Stettler","Stony Plain","Strathmore","Sundre","Swan Hills","Sylvan Lake","Taber","Three Hills","Tofield","Two Hills","Vegreville","Vermilion","Viking","Vulcan","Wainwright","Westlock","Wetaskiwin","Whitecourt","Winkler"],
  "British Columbia": [
    "Abbotsford","Armstrong","Burnaby","Cache Creek","Campbell River","Castlegar","Chilliwack","Colwood","Coquitlam","Courtenay","Cranbrook","Creston","Cumberland","Dawson Creek","Delta","Duncan","Enderby","Fernie","Fort St. James","Fort St. John","Golden","Grand Forks","Hope","Houston","Invermere","Kamloops","Kelowna","Kimberley","Kitimat","Ladysmith","Lake Country","Langford","Langley","Lantzville","Maple Ridge","Merritt","Mission","Nanaimo","Nelson","New Westminster","North Cowichan","North Vancouver","Oak Bay","Oliver","Osoyoos","Parksville","Peachland","Penticton","Pitt Meadows","Port Alberni","Port Coquitlam","Port Hardy","Port Moody","Powell River","Prince George","Prince Rupert","Qualicum Beach","Quesnel","Revelstoke","Richmond","Rossland","Saanich","Salmon Arm","Sidney","Smithers","Squamish","Stewart","Summerland","Surrey","Terrace","Trail","Vancouver","Vernon","Victoria","View Royal","West Kelowna","West Vancouver","White Rock","Williams Lake"],
  "Manitoba": [
    "Altona","Arborg","Beausejour","Birtle","Boissevain","Brandon","Carberry","Carman","Dauphin","Deloraine","Emerson","Flin Flon","Gimli","Gladstone","Glenboro","Grandview","Hamiota","Hartney","Lac du Bonnet","Leaf Rapids","MacGregor","Melita","Minnedosa","Morden","Morris","Neepawa","Niverville","Norway House","Portage la Prairie","Reston","Riverton","Roblin","Russell","Sainte Anne","Selkirk","Shoal Lake","Souris","Sprague","Steinbach","Stonewall","Swan River","The Pas","Thompson","Virden","Winkler","Winnipeg","Winnipegosis"],
  "New Brunswick": [
    "Alma","Atholville","Bathurst","Belledune","Boiestown","Campbellton","Cap-Pelé","Caraquet","Dalhousie","Dieppe","Edmundston","Florenceville-Bristol","Fredericton","Fundy-St. Martins","Gagetown","Grand Bay-Westfield","Grand Falls","Hampton","Hartland","Lamèque","Miramichi","Moncton","Oromocto","Perth-Andover","Petitcodiac","Quispamsis","Rexton","Richibucto","Riverview","Rothesay","Sackville","Saint Andrews","Saint John","Saint-Quentin","Salisbury","Shediac","Shippagan","Souris","Sussex","Tracadie","Woodstock"],
  "Newfoundland and Labrador": [
    "Bay Roberts","Bishop's Falls","Bonavista","Botwood","Buchans","Carbonear","Channel-Port aux Basques","Clarenville","Corner Brook","Deer Lake","Fogo Island","Fortune","Gander","Grand Bank","Grand Falls-Windsor","Happy Valley-Goose Bay","Harbour Grace","Labrador City","Lewisporte","Marystown","Mount Pearl","Musgravetown","Paradise","Placentia","Springdale","St. Alban's","St. Anthony","St. John's","Stephenville","Torbay","Wabush","Whitbourne","Windsor"],
  "Nova Scotia": [
    "Amherst","Antigonish","Berwick","Bridgewater","Clark's Harbour","Dartmouth","Digby","Glace Bay","Halifax","Hantsport","Kentville","Lockeport","Lunenburg","Mahone Bay","Middleton","Mulgrave","New Glasgow","New Waterford","Oxford","Parrsboro","Pictou","Port Hawkesbury","Sheet Harbour","Shelburne","Springhill","Stellarton","Stewiacke","Sydney","Trenton","Truro","Westville","Windsor","Wolfville","Yarmouth"],
  "Ontario": [
    "Ajax","Algonquin Highlands","Alnwick/Haldimand","Amherstburg","Aurora","Bancroft","Barrie","Belleville","Blind River","Bracebridge","Bradford West Gwillimbury","Brampton","Brant","Brantford","Brockville","Burlington","Caledon","Cambridge","Carleton Place","Chatham-Kent","Clarence-Rockland","Cobourg","Cochrane","Collingwood","Cornwall","Deep River","Dryden","Durham","Elliot Lake","Espanola","Essex","Fort Erie","Fort Frances","Gananoque","Georgina","Gravenhurst","Greater Sudbury","Greenstone","Grimsby","Guelph","Haldimand County","Halton Hills","Hamilton","Hanover","Hearst","Huntsville","Ingersoll","Innisfil","Iroquois Falls","Kapuskasing","Kawartha Lakes","Kenora","Kincardine","Kingston","Kirkland Lake","Kitchener","Lakeshore","LaSalle","Leamington","Lincoln","Lindsay","Listowel","London","Markham","Mattawa","Midland","Milton","Mississauga","Mono","Moosonee","Napanee","New Tecumseth","Newmarket","Niagara Falls","Niagara-on-the-Lake","Norfolk County","North Bay","North Perth","Oakville","Orangeville","Orillia","Oshawa","Ottawa","Owen Sound","Parry Sound","Pelham","Pembroke","Perth","Petawawa","Peterborough","Pickering","Port Colborne","Port Hope","Prince Edward County","Quinte West","Renfrew","Richmond Hill","Sarnia","Sault Ste. Marie","Shelburne","Sioux Lookout","Smiths Falls","St. Catharines","St. Thomas","Stratford","Strathroy-Caradoc","Temiskaming Shores","Thorold","Thunder Bay","Tillsonburg","Timmins","Toronto","Vaughan","Wawa","Welland","Whitby","Whitchurch-Stouffville","Windsor","Woodstock"],
  "Prince Edward Island": [
    "Alberton","Belfast","Charlottetown","Cornwall","Georgetown","Hunter River","Kensington","Montague","Morell","Mount Stewart","Murray Harbour","Murray River","North Rustico","O'Leary","Souris","Stratford","Summerside","Tignish","Wellington"],
  "Quebec": [
    "Alma","Amos","Baie-Comeau","Baie-Saint-Paul","Beaconsfield","Beaupré","Blainville","Bois-des-Filion","Boisbriand","Boucherville","Brossard","Candiac","Cap-Rouge","Chambly","Châteauguay","Chibougamau","Côte-Saint-Luc","Coteau-du-Lac","Delson","Deux-Montagnes","Dolbeau-Mistassini","Dollard-des-Ormeaux","Donnacona","Dorval","Drummondville","Farnham","Fermont","Forestville","Gaspé","Gatineau","Granby","Joliette","Kirkland","L'Ancienne-Lorette","La Prairie","La Sarre","La Tuque","Lac-Mégantic","Lachute","Laval","Lemoyne","Lévis","Longueuil","Lorraine","Louiseville","Magog","Mascouche","Matane","Mont-Joli","Mont-Laurier","Mont-Royal","Mont-Saint-Hilaire","Montréal","Montréal-Est","Mirabel","Nicolet","Notre-Dame-des-Prairies","Pincourt","Plessisville","Pointe-Claire","Princeville","Québec City","Rawdon","Repentigny","Rimouski","Rivière-du-Loup","Roberval","Rouyn-Noranda","Sainte-Adèle","Sainte-Agathe-des-Monts","Sainte-Julie","Sainte-Marie","Sainte-Thérèse","Saint-Bruno-de-Montarville","Saint-Constant","Saint-Eustache","Saint-Georges","Saint-Hyacinthe","Saint-Jean-sur-Richelieu","Saint-Jérôme","Saint-Lambert","Salaberry-de-Valleyfield","Sept-Îles","Shawinigan","Sherbrooke","Sorel-Tracy","Terrebonne","Thetford Mines","Trois-Rivières","Val-d'Or","Varennes","Vaudreuil-Dorion","Victoriaville","Westmount"],
  "Saskatchewan": [
    "Assiniboia","Battleford","Biggar","Canora","Carlyle","Carnduff","Creighton","Davidson","Estevan","Esterhazy","Eston","Flin Flon","Gravelbourg","Grenfell","Hudson Bay","Humboldt","Indian Head","Kindersley","Kipling","La Ronge","Langenburg","Langham","Lloydminster","Lumsden","Macklin","Maple Creek","Martensville","Meadow Lake","Melfort","Melville","Moose Jaw","Moosomin","Nipawin","North Battleford","Outlook","Oxbow","Pilot Butte","Ponteix","Prince Albert","Regina","Rosetown","Rosthern","Saskatoon","Shaunavon","Shellbrook","Spiritwood","Swift Current","Tisdale","Unity","Wadena","Warman","Watrous","Weyburn","White City","Whitewood","Wilkie","Wynyard","Yorkton","Zeballos"],
  "Northwest Territories": [
    "Behchokǫ̀","Colville Lake","Deline","Dettah","Enterprise","Fort Good Hope","Fort Liard","Fort McPherson","Fort Providence","Fort Resolution","Fort Simpson","Fort Smith","Gameti","Hay River","Inuvik","Jean Marie River","Kakisa","Lutselk'e","Nahanni Butte","Norman Wells","Paulatuk","Sachs Harbour","Tsiigehtchic","Tuktoyaktuk","Tulita","Ulukhaktok","Whati","Yellowknife","Wrigley"],
  "Nunavut": [
    "Arctic Bay","Arviat","Baker Lake","Cambridge Bay","Cape Dorset","Chesterfield Inlet","Clyde River","Coral Harbour","Gjoa Haven","Grise Fiord","Hall Beach","Igloolik","Iqaluit","Kimmirut","Kinngait","Kugaaruk","Kugluktuk","Pangnirtung","Paulatuk","Pelly Bay","Pond Inlet","Qikiqtarjuaq","Rankin Inlet","Repulse Bay","Resolute","Sanikiluaq","Taloyoak","Whale Cove"],
  "Yukon": [
    "Burwash Landing","Carcross","Carmacks","Dawson City","Destruction Bay","Faro","Haines Junction","Johnson's Crossing","Keno City","Mayo","Old Crow","Pelly Crossing","Ross River","Teslin","Watson Lake","Whitehorse"],
};

export default CANADA_MUNICIPALITIES;